<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Category\Interfaces\" />
    <Folder Include="Category\Validations\" />
    <Folder Include="Products\Interfaces\" />
    <Folder Include="Products\Validations\" />
  </ItemGroup>

</Project>
