@Backend_HostAddress = https://localhost:7165

GET {{Backend_HostAddress}}/api/products

###

POST {{Backend_HostAddress}}/api/products
Content-Type: application/json

{
  "name":"prueba",
  "description": "Prueba",
  "creationDate": "1982-05-13T00:00:00"
}

###
