@Backend_HostAddress = https://localhost:7165

// AddPerson
POST {{Backend_HostAddress}}/api/people
Content-Type: application/json
{
    "FirstName": "prueba",
    "LastName": "Test",
    "Telephone": "666777888",
    "BirthDate": "1982-05-13T00:00:00.0000000"
}

###
// GetPeople
GET {{Backend_HostAddress}}/api/people

###

DELETE {{Backend_HostAddress}}/api/people/2

###

GET {{Backend_HostAddress}}/api/people/4

###

PUT {{Backend_HostAddress}}/api/people/4
Content-Type: application/json

{
  "id": 4,
    "firstName": "Test",
  "lastName": "Prueba",
  "birthDate": "1982-05-13T00:00:00",
  "telephone": "666777888"
}

###

GET {{Backend_HostAddress}}/api/people

###
